# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReservationService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18ReservationService.proto\x12\x0f\x61pi.grpc.server\"l\n\x12ReservationRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x12\n\nstart_date\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x05 \x01(\t\"U\n\x13ReservationResponse\x12\x14\n\x0c\x61vailability\x18\x01 \x01(\x08\x12\x12\n\ndaily_rate\x18\x02 \x01(\x01\x12\x14\n\x0ctotal_amount\x18\x03 \x01(\x01\x32t\n\x12ReservationService\x12^\n\x0fMakeReservation\x12#.api.grpc.server.ReservationRequest\x1a$.api.grpc.server.ReservationResponse\"\x00\x42\t\n\x05protoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ReservationService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'\n\005protoP\001'
    _RESERVATIONREQUEST._serialized_start = 45
    _RESERVATIONREQUEST._serialized_end = 153
    _RESERVATIONRESPONSE._serialized_start = 155
    _RESERVATIONRESPONSE._serialized_end = 240
    _RESERVATIONSERVICE._serialized_start = 242
    _RESERVATIONSERVICE._serialized_end = 358
# @@protoc_insertion_point(module_scope)
