# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ReservationService_pb2 as ReservationService__pb2


class ReservationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeReservation = channel.unary_unary(
                '/api.grpc.server.ReservationService/MakeReservation',
                request_serializer=ReservationService__pb2.ReservationRequest.SerializeToString,
                response_deserializer=ReservationService__pb2.ReservationResponse.FromString,
                )


class ReservationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MakeReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReservationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeReservation,
                    request_deserializer=ReservationService__pb2.ReservationRequest.FromString,
                    response_serializer=ReservationService__pb2.ReservationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.grpc.server.ReservationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReservationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakeReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.grpc.server.ReservationService/MakeReservation',
            ReservationService__pb2.ReservationRequest.SerializeToString,
            ReservationService__pb2.ReservationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
